name: lhs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - plotly==5.2.1
  - python-kaleido
  - ipykernel
  - nbformat
  - xarray
  - cartopy
